application: agambrahma
version: 1
runtime: go
api_version: go1

handlers:
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /
  static_files: static/html/index.html
  upload: static/html/index.html

- url: /helloworld
  script: _go_app

- url: /.*
  static_files: static/html/404.html
  upload: static/html/404.html


