application: agambrahma
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: index.py

- url: /index\.html
  script: index.py

- url: /tasks/fetchposterous
  script: fetchposterous.py
  login: admin

- url: /blog/.*
  script: blog.py

- url: /posterous/.*
  script: posterous.py

- url: /static
  static_dir: static

- url: /_ah/mail/blogpost@agambrahma\.appspot\.com
  script: blog_post_email.py

- url: /.*
  static_files: static/html/404.html
  upload: static/html/404.html

inbound_services:
- mail
