application: agambrahma
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py

- url: /main/.*
  script: main.py

- url: /static
  static_dir: static

- url: /.*
  script: not_found.py
